default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  password: '1'

development:
  <<: *default
  database: banner_dev

test:
  <<: *default
  database: banner_test

production:
  <<: *default
  database: banner_prod
